### PR TITLE
Nautilus support

### PR DESCRIPTION
**Pull request by K07H**
**OSubMarin commits:**
-----
* Fixed mod initialization messages not being displayed correctly in BepInEx console.
* Fixed issue with autopilot engine icon not spining correctly in some cases.
* Fixed issue with autopilot routes state not being restored correctly in some cases.
* Fixed issue with autopilot routes not being selected correctly in some cases.
* Added Nautilus support.
* Bumped version numbers.
----
**Merged FirEmerald commits:**
----
* Non-destructive, code for SMLHelper version is intact and can be compiled by fixing the csproj file's subnautica directory, installing SMLHelper, and then using the DebugSML or ReleaseSML configurations.
----
* Replace existing Logger with improved Logger.
* Add additional constructors to BaseItem.
* Automatically copy built DLL to game directory.
----
* Replace simple text-based dock state saving with more robust JSON-based saving.
----
* Re-add saving of docking state to txt file, for compatibility with older versions of the mod (just in case).
----
**OSubMarin post-merge commits:**
-----
* Restored project properties which got replaced with previous merge-commit.
* Remove unused VS solution profiles (DebugSML and ReleaseSML).
* Switched Json save format to an additional save format (instead of default save format), to not break backwards compatibility.
* Removed Json lib dependency.
* Switched INFO logging to MESSAGE logging.
* Restored InvariantCulture in Logger.

### CODE REVIEW

**Comment by FirEmerald** [comment]
I don't want to be annoying but what was the reason behind swapping from Newtonsoft to a custom JSON parser? Newtonsoft is guaranteed available as it's a library that Subnautica itself uses.

**Comment by K07H** [comment]
Because it's the coding standard of my company.
Here are further lectures if you want to get an idea of why this is a common coding standard:
https://builtin.com/software-engineering-perspectives/software-dependency-costs
https://blog.carlana.net/post/2020/avoid-dependencies/
https://blog.codinghorror.com/dependency-avoidance/
https://www.freecodecamp.org/news/code-dependencies-are-the-devil-35ed28b556d/
https://yosefk.com/blog/redundancy-vs-dependencies-which-is-worse.html

**Comment by K07H** [comment]
I added your name in the contributions sections (in mod description, documentation, in messages tab and on Github), but I can remove it if you prefer.
Also I would greatly appreciate if you can give some time to test everything for Decorations Mod because it's a **huge pain** to test everything this mod adds into the game.
Thank you

**Comment by FirEmerald** [comment]
I don't mind that it's there, I just never really cared either way. And the reason I had the JSON take priority is that the text file loading just didn't seem to work properly, and it's kind of messy so I went with a more robust data storage method that I'm familiar with. looking at it again I think it's just missing a single slash in the string, like so in line 14 of BaseFixer.cs:
`text += string.Format(CultureInfo.InvariantCulture, "{0}/{1}/{2}/{3}/{4}/{5}/{6}/{7}/{8}/{9}/{10}/{11}/{12}/{13}{14}", new object[]`
since the file is parsed by splitting around the forward slashes, it should probably be
`text += string.Format(CultureInfo.InvariantCulture, "{0}/{1}/{2}/{3}/{4}/{5}/{6}/{7}/{8}/{9}/{10}/{11}/{12}/{13}/{14}", new object[]`
instead. But it's not my code, it's yours, so I wasn't sure if this was actually the case. Additionally, I don't remember ever seeing errors logged to the console from it, but changing it over to the JSON format did make my game seem a LOT more stable - some objects had been not loading, such as my prawn suit disappearing, an entire locker vanishing, and all the power cells in my cyclops went goodbye as well - so I think it is causing some sort of error during loading that's silently caught but prevents the rest of the game data from being loaded.

**Comment by K07H** [comment]
From what I recall there was 14 values so the concatenation of the last 2 values can make sense. Or I just made a mistake and there's actually 15 values. I will have to check that.

**Comment by K07H** [comment]
I just checked and the 15 element is just the new line character. So there's no problems there.
The problem you faced with saves was due to incorrect selection of save folder path I think, which I fixed in latest update.

**Comment by K07H** [comment]
And now I just realize I did not fix it everywhere (I missed other locations where the fix I did needs to be placed).
EDIT: Well actually maybe the fix doesn't need to be applied to the other locations, it depends if the savegame slot id is properly set in "SaveLoadManager.main.GetCurrentSlot()" when the function retrieving path is called. I will have to test this.
EDIT 2: And another possible inconsistency can come from the fact that I forgot to include the "NumberStyles.AllowThousands" flag when parsing float values, which can cause problems if your Cyclops Docking base piece is located outside of the cube X[-1000;1000] Y[-1000;1000] Z[-1000;1000]. This also needs testing.

**Comment by FirEmerald** [comment]
Weird then that switching to JSON made my game more stable. IDK what's up with that. if that is the case there's really no reason to leave the json there, I only added it originally so I could see what was going on more clearly.

**Comment by K07H** [comment]
Because the loading method sometimes fails if you load another save without fully restarting the game. And I thought I fixed it in latest release v2.1.0 but now I notice it might fail in InGameMenuFixer class as well, so I need to test it.
Another cause of inconsistency can be due to incorrect number parsing: CultureInfo.InvariantCulture is used instead of CultureInfo.InvariantCulture.NumberFormat, and as written above the NumberStyles flags are missing NumberStyles.AllowThousands.

PS: And it's also missing the "G9" format specifier... So yeah obviously there are inconsistencies when writing/reading float values.

**Pull request merged**
